export const AUTH_GOOGLE_SUCCESS = 'AUTH_GOOGLE_SUCCESS' as const;

export const LOGIN_REQUEST_SUCCESS = 'LOGIN_SUCCESS' as const;
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST' as const;
export const LOGIN_REQUEST_FAILURE = 'LOGIN_FAILURE' as const;

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST' as const;
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS' as const;
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE' as const;

export const PERSIST_REHYDRATE = 'persist/REHYDRATE' as const;
